#!/usr/bin/env bash

# Using swap space is a bad idea on Raspberry Pi
sudo dphys-swapfile swapoff

# Update Advanced Packaging Tool (apt) and upgrade packages
sudo apt update && apt upgrade
sudo apt-get update && apt-get upgrade

# Enable snapd
sudo apt install snapd

sudo reboot
